@echo off
setlocal
cd /d "%~dp0"

set "MSG=%*"
if "%MSG%"=="" set "MSG=update 3d models"

git add -A
if errorlevel 1 goto :fail

git commit -m "%MSG%"
if errorlevel 1 (
  echo [INFO] nothing to commit.
  pause
  exit /b 0
)

echo.
echo Committed: %MSG%
echo models.json was regenerated by the pre-commit hook.
echo Push it yourself:  git push
echo.
pause
exit /b 0

:fail
echo [ERROR] git add failed.
pause
exit /b 1
